### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by ReneVolution** [omemo/python-omemo#15]
Hey fellow maintainers,

just wondering if this project is still maintained from your side as there has not been many communication and updates since around June 2016. 

If not, please let me know and we could discuss to transfer ownership for this repo or maybe adding me to the omemo organisation.

Cheers,
René

**Comment by kalkin** [comment]
@ReneVolution the project moved to https://dev.gajim.org/gajim/gajim-plugins. If you want to help your patches will be welcome there.

**Comment by kalkin** [comment]
@ReneVolution Ups wrong repo. I confused it with the gajim-omemo repo. This project is dormant. If you want to help PRs will be accepted by me, if your work is good and steady, I will add you to the orga.

**Comment by ReneVolution** [comment]
I see. Will fork the project then until my work is good and steady enough :). Thanks.
